# In this notebook, play around to figure out derivative of the multi-step process

In [ ]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import seaborn
import scipy.optimize as op
seaborn.set(font_scale=1.5,style='ticks')

In [448]:
A = np.random.normal(size=(5,5))
x = np.random.normal(size=(5,1))


y = A@x + np.random.normal(size=(5,1))

In [449]:
def cost(A,x,y):
    return (A@x-y)[0]**2

In [450]:
Ahat = np.random.normal(size=(5,5))


op.approx_fprime(Ahat,
                 cost,
                 1e-6,
                 *(x,y))

array([ 0.68028084, -6.17601591, -1.92242457, -0.94327094,  0.99201918])

In [451]:
(2*(Ahat@x-y)@x.T)[0]

array([ 0.68028078, -6.17602097, -1.92242506, -0.94327106,  0.99201905])

# Two steps ahead

In [452]:
A = np.random.normal(size=(5,5))
x = np.random.normal(size=(5,1))


y = np.linalg.matrix_power(A,2)@x + np.random.normal(size=(5,1))

Ahat = np.random.normal(size=(5,5))


In [490]:
def cost2(Ad,x,y):
    return sum(((np.linalg.matrix_power(Ad,2)@x-y))**2)

In [491]:


op.approx_fprime(Ahat,
                 cost2,
                 1e-6,
                 *(x,y))

array([ -2.17598421,  -3.65830778, -19.99982288,   7.88798872,
        15.15002795])

In [492]:
i=j= 0
m = 5
e_i = np.zeros(m)
e_j = np.zeros(m)
e_i[i] = 1.
e_j[j] = 1.
E = np.outer(e_i, e_j)

n = 2
D = sum(np.linalg.matrix_power(Ahat, i) @ E @ np.linalg.matrix_power(Ahat, n - i - 1) for i in range(0, n))

In [474]:


op.approx_fprime(Ahat,
                 cost3,
                 1e-6,
                 )

array([  0.90187716,   4.10045213, -10.0628444 ,  -5.33749302,
       -13.62722759])

In [457]:
e = np.zeros(5)
e[0] = 1
E = np.outer(e,e)

In [458]:
tmp = np.zeros([5,5])
for i in range(2):
    tmp += np.linalg.matrix_power(Ahat,i)@E@np.linalg.matrix_power(Ahat,2-i-1)

In [459]:
tmp

array([[-0.72525518,  0.36919555,  0.17883359,  0.16851301, -1.16964967],
       [ 0.14708129,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 2.31145934,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.67067131,  0.        ,  0.        ,  0.        ,  0.        ],
       [-0.04094999,  0.        ,  0.        ,  0.        ,  0.        ]])

In [460]:
2*(np.linalg.matrix_power(Ahat,2)@x-y) *(tmp@x)

array([[-0.62810653],
       [ 0.3060872 ],
       [-6.55063074],
       [-1.07275292],
       [-0.08016505]])

In [461]:
(2*(np.linalg.matrix_power(Ahat,2)@x-y)@((tmp@x).T))[0]

array([-0.62810653, -0.25453476, -4.00014661, -2.89121685,  0.0708669 ])

In [462]:
evals,evecs = np.linalg.eig(Ahat)

In [278]:
(A[0]@x + A[0,0]**2 * x[0])

array([1.07678173])

In [270]:
(4*(np.linalg.matrix_power(Ahat,2)@x-y)@((Ahat.T@x).T))

array([[ -45.26875374,   29.79335572,  -41.53599406,  150.06983201,
          24.42272071],
       [ -54.08014821,   35.59252155,  -49.62082074,  179.28036639,
          29.17651241],
       [ -36.81144214,   24.22722738,  -33.77605336,  122.03311293,
          19.85995849],
       [ -55.55782451,   36.56504524,  -50.97665118,  184.17899107,
          29.97372622],
       [  38.70797959,  -25.475422  ,   35.51620659, -128.32029853,
         -20.88315   ]])

In [84]:

A@A

array([[-3.0749895 ,  2.27633336,  0.12132083,  0.98921866,  3.39335858],
       [-5.91608917,  1.53606772, -5.12562965, -0.11359664,  3.3046313 ],
       [ 4.56501482,  1.80303031,  7.00232585,  1.79403965, -2.54782167],
       [-1.39829355,  1.33088184,  0.37647531,  0.97128993, -0.45873432],
       [-1.47776503,  2.45425331,  1.9255465 , -0.58754651,  4.04081471]])

In [85]:

def cost(A,x)
    np.linalg.matrix_power(A,2)

array([[-3.0749895 ,  2.27633336,  0.12132083,  0.98921866,  3.39335858],
       [-5.91608917,  1.53606772, -5.12562965, -0.11359664,  3.3046313 ],
       [ 4.56501482,  1.80303031,  7.00232585,  1.79403965, -2.54782167],
       [-1.39829355,  1.33088184,  0.37647531,  0.97128993, -0.45873432],
       [-1.47776503,  2.45425331,  1.9255465 , -0.58754651,  4.04081471]])

In [271]:
np.linalg.matrix_power(A,20)@x

array([[  4926.62007021],
       [ -6712.73889025],
       [-11486.87727486],
       [  1898.15367907],
       [ 12516.10889532]])

In [301]:
z = np.zeros(5)
z[0] = (A[0]@x + A[0,0] * x[0])
z[1:] = A[1:,0]

In [302]:
np.dot(2*(np.linalg.matrix_power(Ahat,2)@x-y).T,z)

array([-24.38017597])

# Run with jax

In [608]:
A = np.random.normal(size=(5,5))
x = np.random.normal(size=(5,1))


y = np.linalg.matrix_power(A,2)@x #+ np.random.normal(size=(5,1))

Ahat = np.random.normal(size=(5,5))


In [609]:
import jax.numpy as jnp
from jax import grad, jit, vmap
from jax import random


In [610]:
def predict(Ahat,x,y):
    Ahat = jnp.reshape(Ahat,(5,5))
    return jnp.sum((jnp.dot(jnp.linalg.matrix_power(Ahat,2),x)-y)**2)

In [611]:

grad_predict = grad(predict)

def grad_wrap(Ahat,x,y):
    #Ahat = jnp.reshape(Ahat,(5,5))
    return np.array(grad_predict(Ahat,x,y)).flatten()

In [612]:
grad_wrap(Ahat,x,y)

array([-38.4132    ,  12.734225  ,  -8.72143   , -10.775151  ,
       -19.905865  ,   6.081798  ,   0.99771005,  -1.5816524 ,
         3.3724425 ,  -0.5580479 , -53.747536  , -18.807701  ,
        23.79792   , -35.327816  ,  17.228657  , -33.07635   ,
        23.738226  , -20.065157  ,  -2.2154346 , -32.862366  ,
       -72.678795  ,  17.843946  , -10.358186  , -23.842436  ,
       -29.970087  ], dtype=float32)

In [613]:
predict(A,x,y)

DeviceArray(4.5474735e-13, dtype=float32)

In [614]:
res = op.minimize(predict,
           Ahat.flatten(),
           (x,y),
           jac=grad_wrap,
           method='BFGS'
           )

array([[-1.22460316,  0.72622814,  0.50708658,  0.54978612, -1.00648622],
       [ 1.82127266, -1.06875035,  1.47263374,  0.38960624,  1.29957188],
       [ 0.54046966,  0.7858748 ,  2.30273027,  0.88306787,  0.72985877],
       [-0.34367772, -1.15917902, -1.96031598, -0.9978303 , -1.41348504],
       [ 0.21099819, -0.84988989, -1.82750732, -1.73886696, -0.69337155]])

In [618]:
np.linalg.matrix_power(res.x.reshape(5,5),2)@x

array([[ 4.36784692],
       [-5.1965338 ],
       [ 2.36050634],
       [-2.71350226],
       [-2.28097974]])

In [619]:
y

array([[ 4.36784739],
       [-5.19653372],
       [ 2.36050631],
       [-2.71350261],
       [-2.28098008]])

# Now do full simulation 